version: '3.8'

services:
  vibe-monitor:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL:-http://localhost:8000}
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - vibe-monitor-network

networks:
  vibe-monitor-network:
    driver: bridge