name: Vercel Production (Deploy Hook)

on:
  push:
    branches: [ main ]

jobs:
  deploy_prod:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel Production Deploy
        run: |
          curl -s -X POST "$VERCEL_DEPLOY_HOOK_PROD"
        env:
          VERCEL_DEPLOY_HOOK_PROD: ${{ secrets.VERCEL_DEPLOY_HOOK_PROD }}
