name: Vercel Preview (Deploy Hook)

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  deploy_preview:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel Preview Deploy
        run: |
          curl -s -X POST "$VERCEL_DEPLOY_HOOK_PREVIEW"
        env:
          VERCEL_DEPLOY_HOOK_PREVIEW: ${{ secrets.VERCEL_DEPLOY_HOOK_PREVIEW }}
